name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JavaScript file
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: node my_script.js
