name: Deploy UTM Function

on:
  push:
    branches:
      - main  # 选择你想要触发的分支，比如 main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 升级到 v3

    - name: Install Node.js
      uses: actions/setup-node@v4  # 升级到 v4
      with:
        node-version: '20'  # 使用 Node.js 20，或指定其他你需要的版本

    - name: Install dependencies
      run: npm install

    - name: Run UTM Function Script
      run: |
        node utm-function.js
      env:
        BITLY: ${{ secrets.BITLY }}
        REURL: ${{ secrets.REURL }}
        TINYURL: ${{ secrets.TINYURL }}
        REBRANDLY: ${{ secrets.REBRANDLY }}
